### ISSUE TITLE
Interval comparisons

### ISSUE THREAD

**Issue by KayaHub** [hipa-org/HIPA-CLI#5]
So far each interval is compared to the previous one. However, that does not necessarily provide a whole lot of information. It would be useful to compare all intervals with the baseline interval and to the respective previous one.

For example:
3 intervals: 

1. baseline (BL)
2. addition A (A)
3. addition B (B)

compare both A & B to baseline e.g. A reaches higher values than BL so activation will be true. However, B does reach higher values than A, hence comparing A to B will lead to activation = false. However, B could still reach higher levels when compared to BL for example if the intensity values are between BL & A. So B would be activation = true when compared to BL but activation = false when compared to A. 

With the current system activation for B would be false for this example and the information that B did reach higher levels than BL would get lost.

**Comment by Exitare** [comment]
Implemented with ae6428275a4ad81a34627483991364e0ed120f70
